spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cafefolio?autoReconnect=true
    username: root
  jpa:
    hibernate:
      auto-ddl: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        show_sql: true